version: "3.7"
services:
  db:
    image: postgres:11.7
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres-data:
    external: true

# https://github.com/docker/for-win/issues/445
# docker volume create --name postgres-data -d local
