version: "3.7"
services:
  db:
    image: postgres:11.7
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
  cache:
    image: redis:6.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: "redis-server --appendonly yes"

volumes:
  postgres-data:
    external: true
  redis-data:
    external: true

# https://github.com/docker/for-win/issues/445
# docker volume create --name postgres-data -d local

# docker exec -it #id sh
